export const definitions = [
  `Account means a unique account created for You to access our Service or parts of our Service.`,
  `Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to The Net VR Inc.`,
  `Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.`,
  `Country refers to: Oregon, United States`,
  `Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.`,
  `Personal Data is any information that relates to an identified or identifiable individual.`,
  `Service refers to the Website.`,
  `Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.`,
  `Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.`,
  `Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).`,
  `You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.`
]

export const personalData = [
  "Email Address",
  "First Name and Last Name",
  "Phone Number",
  "Address, State, Province, ZIP/Postal Code, City",
  "Usage Data"
]

export const usageData = [
  "Usage Data is collected automatically when using the Service.",
  "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
  "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device you use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
  "We may also collect information that your browser sends whenever you visit our service or when you access the service by or through a mobile device."
]

export const socialMediaData = [
  `If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.`,
  `You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.`
]

export const cookies = {
  points: [
    `Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.`,
    `Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).`
  ],
  purposes: [
    {
      name: "Necessary / Essential Cookies",
      type: "Persistent Cookies",
      administeredBy: "Us",
      purpose: "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services."
    },
    {
      name: "Cookies Policy / Notice Acceptance Cookies",
      type: "Session Cookies",
      administeredBy: "Us",
      purpose: "These Cookies identify if users have accepted the use of cookies on the Website."
    },
    {
      name: "Functionality Cookies",
      type: "Persistent Cookies",
      administeredBy: "Us",
      purpose: "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website."
    },
  ]
}