// policy page
export const definitions = [
  `Account means a unique account created for You to access our Service or parts of our Service.`,
  `Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to The Net VR Inc.`,
  `Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.`,
  `Country refers to: Oregon, United States`,
  `Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.`,
  `Personal Data is any information that relates to an identified or identifiable individual.`,
  `Service refers to the Website.`,
  `Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.`,
  `Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.`,
  `Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).`,
  `You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.`
]

export const personalData = [
  "Email Address",
  "First Name and Last Name",
  "Phone Number",
  "Address, State, Province, ZIP/Postal Code, City",
  "Usage Data"
]

export const usageData = [
  "Usage Data is collected automatically when using the Service.",
  "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
  "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device you use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
  "We may also collect information that your browser sends whenever you visit our service or when you access the service by or through a mobile device."
]

export const socialMediaData = [
  `If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.`,
  `You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.`
]

export const cookies = {
  points: [
    `Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.`,
    `Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).`
  ],
  purposes: [
    {
      name: "Necessary / Essential Cookies",
      type: "Persistent Cookies",
      administeredBy: "Us",
      purpose: "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services."
    },
    {
      name: "Cookies Policy / Notice Acceptance Cookies",
      type: "Session Cookies",
      administeredBy: "Us",
      purpose: "These Cookies identify if users have accepted the use of cookies on the Website."
    },
    {
      name: "Functionality Cookies",
      type: "Persistent Cookies",
      administeredBy: "Us",
      purpose: "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website."
    },
  ]
}

export const useOfPersonalData = {
  section1: [
    `To provide and maintain our Service, including to monitor the
    usage of our Service.`,
    `To manage Your Account: to manage Your registration as a user of
    the Service. The Personal Data You provide can give You access to
    different functionalities of the Service that are available to You
    as a registered user.`,
    `For the performance of a contract: the development, compliance and
    undertaking of the purchase contract for the products, items or
    services You have purchased or of any other contract with Us
    through the Service.`,
    `To contact You: To contact You by email, telephone calls, SMS, or
    other equivalent forms of electronic communication, such as a
    mobile application's push notifications regarding updates or
    informative communications related to the functionalities,
    products or contracted services, including the security updates,
    when necessary or reasonable for their implementation.`,
    `To provide You with news, special offers and general information
    about other goods, services and events which we offer that are
    similar to those that you have already purchased or enquired about
    unless You have opted not to receive such information.`,
    `To manage Your requests: To attend and manage Your requests to Us.`,
    `For business transfers: We may use Your information to evaluate or
    conduct a merger, divestiture, restructuring, reorganization,
    dissolution, or other sale or transfer of some or all of Our
    assets, whether as a going concern or as part of bankruptcy,
    liquidation, or similar proceeding, in which Personal Data held by
    Us about our Service users is among the assets transferred.`,
    `For other purposes: We may use Your information for other
    purposes, such as data analysis, identifying usage trends,
    determining the effectiveness of our promotional campaigns and to
    evaluate and improve our Service, products, services, marketing
    and your experience.`,
  ],
  section2: [
    `With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.`,
    `For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.`,
    `With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.`,
    `With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.`,
    `With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.`,
    `With Your consent: We may disclose Your personal information for any other purpose with Your consent.`
  ]
}

export const retentionOfPersonalData = [
  `The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.`,
  `The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.`
]

export const transferOfYourPersonalData = [
  `Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.`,
  `Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.`,
  `The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.`
]

export const deleteYourPersonalData = [
  `You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.`,
  `Our Service may give You the ability to delete certain information about You from within the Service.`,
  `You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.`,
  `Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.`
]

export const legalRequirements = [
  "Comply with a legal obligation",
  "Protect and defend the rights or property of the Company",
  "Prevent or investigate possible wrongdoing in connection with the Service",
  "Protect the personal safety of Users of the Service or the public",
  "Protect against legal liability"
]

// influencer program
import netVRstream from "../assets/influencerProgram/netVRstream.png";
import twitch from "../assets/influencerProgram/twitch.png";
import youtube from "../assets/influencerProgram/youtube.png";
import facebook from "../assets/influencerProgram/facebook.png";

export const platforms = [
  {
    description: "Host with the NetvrStream.com",
    image: netVRstream
  },
  {
    description: "Host with Twitch",
    image: twitch
  },
  {
    description: "In development",
    image: youtube
  },
  {
    description: "To be developed",
    image: facebook
  },
]

export const netVRTheaterPoints = {
  features: [
    "Direct Stream",
    "Twitch Add-On",
    "Voting Podium",
    "Voice Chat",
    "Donation Podium",
    "Chat Wall",
    "Customized Avatar",
    "Admin Panel"
  ],
  userViewers: [
    "Voice Chat",
    "Integrated Chat Wall",
    "Customizable Avatar",
    "Voting Podium",
    "Award Podium",
    "Seating",
    "Emotes"
  ],
  contentCreatorsFeatures: [
    "Host Your Own Stream",
    "Host Your Favorite Creator, But Be Sure to Get Their Permission",
    ["Admins", "- Highlight", "- Kick", "- Silence", "- Doorway to Other Theater"],
    "Choose Your Own Theater Skin",
    "Upload Your Logo*",
    "Create Your Own Digital Assets"
  ],
  inShopPurchase: [
    ["Immediate Unlock*", "- Text Chat", "- Voice Chat", "- Avatar"],
    "Lux",
    "Lux Ray",
    "Avatar Skin",
    "Awards"
  ],
  inShopPurchase2: [
    ["Immediate Unlock", "- Host"],
    "Extra Seats",
    "Theater Skins",
    "In-theater Items",
    "Award Podium",
    "Seating",
    "Emotes"
  ],
  commandDefinitions: [
    "General Theater Information",
    "Alerts When Users Enter/Leave, Vote, Award",
    "Highlights User",
    "Removes User",
    "Mutes User (Voice Chat)"
  ],
  chatCommand: [
    "!Theater Info",
    "!Theater alerts (on/off)",
    "!Theater highlight (username)",
    "!Theater kick (username)",
    "!Theater silence (username)"
  ],
  windows10: [
    "Processor: Intel Core 2 Duo 2.5 GHz (Or Greater)",
    "DirectX: Version 11",
    "Storage: 2 GB Available Space",
    "Memory: 1 GB RAM",
    "Graphics: NVIDIA 9xxx / ATI 2xxx (Or Greater)",
    "Sound Card: DirectX9 Compatible"
  ],
  macOS10: [
    "Processor: 1.6 GHz Core I5 (I5-8210Y (Or Greater)",
    "Memory: 8 MB",
    "Storage: 2GB Available Space"
  ]
}

import KyleImage from "../assets/ProfilePictures/KyleImage.png";
import BruinImage from "../assets/BruinImage.png";
import SusanImage from "../assets/SusanImage.png";
import DavidImage from "../assets/ProfilePictures/DavidImage.png";
import MikeImage from "../assets/ProfilePictures/MikeXieImage.Jpeg";
import AbdulImage from "../assets/ProfilePictures/AbdulHannanImage.png";
import AlanImage from "../assets/ProfilePictures/AlanTuckerImage.jpg";
import NoahImage from "../assets/ProfilePictures/NoahFajardaImage.png";
import SarahImage from "../assets/ProfilePictures/SarahKugelmasImage.jpg";
import YupengImage from "../assets/ProfilePictures/YupengImage.jpeg";
import NoProfile from "../assets/NoProfilePic.png";

export const teamMembers = [
  {
    name: "Kyle Doran",
    image: KyleImage,
    role: "Chief executive Officer (CEO)",
    description: `Kyle Is Currently The Co-Founder And CEO Of The Net VR. He
      Has A Bachelor Of Science Degree From Oregon State
      University With A Focus In Engineering And Business. Kyle's
      First Stint Of VR Dates Back To The Launch Of The Nintendo
      Virtual Boy In 1995. He Has Been Passionate About Gaming
      Ever Since. Another Passion Of His Is Continually Striving
      To Be A Positive Leader So It Is Only Fitting He Has Become
      As Such Of A Growing Gaming Company.`,
  },
  {
    name: "Bruin Peyton",
    image: BruinImage,
    position: "Chief Technology Officer (CTO)",
    description:
      `Bruin Is Currently The Co-Founder And CTO Of The Net VR. Bruin Is A 
      Self-Taught Developer With Over 20 Years Of Experience. He Has Lead Several 
      Teams Within Corporate IT Before Co-Founding The Company. His Primary Expertise 
      Includes C#, Databases, Networking And Unity`,
  },
  {
    name: "Susan Sunwoo",
    image: SusanImage,
    position: "Chief Operations Officer (COO)",
    description:
      `Susan Is Currently The COO Of The Net VR And An E-Commerce Entrepreneur With 
      A Successful Stationary Company. She Is A Graduate Of The University Of Houston 
      With A Bachelor Of Business Administration Degree In Finance And Marketing. In Her 
      Personal Life She Co-Founded An Event And Movement For Self Growth, Mental Health 
      And Community Called Define And Flourish. D&F's Motto Was 'Define Your Passion And 
      Flourish In Life'. She Discovered Gaming At The Age Of 6 Playing Nintendo Then 
      Moved Onto PC Gaming And Hasn't Stopped Since`,
  },
  {
    name: "David Griffin",
    image: DavidImage,
    position: "Chief Financial Officer (CFO)",
    description:
      `David Is Currently The CFO Of The Net VR. He Has A Bachelor Of Science Degree From 
      The University Of Oregon, With Majors In Mathematics And Economics And Minors In 
      Business, Chemistry, And Political Science. He Has Over 15 Years Of Self-Employment 
      And Consulting Experience, And Has Spent The Last 7 Years As A Digital Nomad`,
  },
  {
    name: "Mike Xie",
    image: MikeImage,
    position: "Chief Technology Officer (CTO)",
    description:
      `Mike is currently the Co-Founder and CTO of the Net VR. He has played almost every 
      genre of video game and loves to understand the meta-game of each one that he has 
      played.`,
  },
  {
    name: "Noah Fajarda",
    image: NoahImage,
    position: "Software Developer",
    description:
      `Noah is a graduate from the University of California, Irvine. He has experience in 
      developing highly-scalable Full-Stack Applications. He enjoys traveling to different 
      countries, analyzing and playing different sports. 
      Link to Website: https://noahfajarda.vercel.app/`,
  },
  {
    name: "Yupeng Zheng",
    image: YupengImage,
    position: "Software Developer",
    description:
      `Yupeng graduated from the University of the Pacific with a Bachelor of Science degree.
       He possesses experience in software development and web application design. 
       He is both a technology lover and a car enthusiast.`,
  },
  {
    name: "Sarah Kugelmas",
    image: SarahImage,
    position: "Software Developer",
    description:
      `Sarah graduated from Case Western Reserve University with a Bachelor's of Science 
      in Computer Science. She grew up in New York, went to college in Cleveland, Ohio, 
      and now resides in the Research Triangle, North Carolina.`,
  },

  {
    name: "Samuel Oyeneyin",
    image: NoProfile,
    position: "Software Developer",
    description:
      `Samuel Oyeneyin is Currently a Software Developer at The NetVR`,
  },
  {
    name: "Abdul Hannan",
    image: AbdulImage,
    position: "Software Developer",
    description:
      `Hannan is from Karachi, Pakistan. He loves reading novels and cooking (picked up 
        chess these days but things ain't looking good) Being from Pakistan, there aren't
         a lot of people who share his hobbies and interests so he enjoys the internet a lot.`,
  },
  {
    name: "Samuel Gbenga",
    image: NoProfile,
    position: "UI/UX Designer",
    description: `Samuel Gbenga is Currently a Ui/UX Designer at The NetVR`,
  },
];