export const definitions = [
  `Account means a unique account created for You to access our Service or parts of our Service.`,
  `Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to The Net VR Inc.`,
  `Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.`,
  `Country refers to: Oregon, United States`,
  `Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.`,
  `Personal Data is any information that relates to an identified or identifiable individual.`,
  `Service refers to the Website.`,
  `Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.`,
  `Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.`,
  `Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).`,
  `You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.`
]

export const personalData = [
  "Email Address",
  "First Name and Last Name",
  "Phone Number",
  "Address, State, Province, ZIP/Postal Code, City",
  "Usage Data"
]

export const usageData = [
  "Usage Data is collected automatically when using the Service.",
  "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
  "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device you use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
  "We may also collect information that your browser sends whenever you visit our service or when you access the service by or through a mobile device."
]

export const socialMediaData = [
  `If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.`,
  `You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.`
]

export const cookies = {
  points: [
    `Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.`,
    `Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).`
  ],
  purposes: [
    {
      name: "Necessary / Essential Cookies",
      type: "Persistent Cookies",
      administeredBy: "Us",
      purpose: "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services."
    },
    {
      name: "Cookies Policy / Notice Acceptance Cookies",
      type: "Session Cookies",
      administeredBy: "Us",
      purpose: "These Cookies identify if users have accepted the use of cookies on the Website."
    },
    {
      name: "Functionality Cookies",
      type: "Persistent Cookies",
      administeredBy: "Us",
      purpose: "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website."
    },
  ]
}

export const useOfPersonalData = {
  section1: [
    `To provide and maintain our Service, including to monitor the
    usage of our Service.`,
    `To manage Your Account: to manage Your registration as a user of
    the Service. The Personal Data You provide can give You access to
    different functionalities of the Service that are available to You
    as a registered user.`,
    `For the performance of a contract: the development, compliance and
    undertaking of the purchase contract for the products, items or
    services You have purchased or of any other contract with Us
    through the Service.`,
    `To contact You: To contact You by email, telephone calls, SMS, or
    other equivalent forms of electronic communication, such as a
    mobile application's push notifications regarding updates or
    informative communications related to the functionalities,
    products or contracted services, including the security updates,
    when necessary or reasonable for their implementation.`,
    `To provide You with news, special offers and general information
    about other goods, services and events which we offer that are
    similar to those that you have already purchased or enquired about
    unless You have opted not to receive such information.`,
    `To manage Your requests: To attend and manage Your requests to Us.`,
    `For business transfers: We may use Your information to evaluate or
    conduct a merger, divestiture, restructuring, reorganization,
    dissolution, or other sale or transfer of some or all of Our
    assets, whether as a going concern or as part of bankruptcy,
    liquidation, or similar proceeding, in which Personal Data held by
    Us about our Service users is among the assets transferred.`,
    `For other purposes: We may use Your information for other
    purposes, such as data analysis, identifying usage trends,
    determining the effectiveness of our promotional campaigns and to
    evaluate and improve our Service, products, services, marketing
    and your experience.`,
  ],
  section2: [
    `With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.`,
    `For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.`,
    `With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.`,
    `With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.`,
    `With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.`,
    `With Your consent: We may disclose Your personal information for any other purpose with Your consent.`
  ]
}
